### ISSUE TITLE
Refactor existing todo list code into components

### ISSUE THREAD

**Issue by chenga3** [chenga3/Producktivity#2]
- [ ] Create 'Add Todos' component
- [ ] Switch to custom button component
- [ ] Review service pattern code
- [ ] Add comments
